In [ ]:
import pandas as pd


In [ ]:
df = pd.read_csv("/content/heart_attack_prediction_dataset_edit1.csv")

In [ ]:
df.shape

(999, 26)

In [ ]:
df.head()

Patient ID   Age     Sex  Cholesterol Blood Pressure  Heart Rate  Diabetes  \
0    BMW7812  67.0       m          208         158/88          72       0.0   
1    CZE1114  21.0    male          389         165/93          98       1.0   
2    BNI9906  21.0  Female          324         174/99          72       1.0   
3    JLN3497  84.0     NaN          383        163/100          73       1.0   
4    GFO8847  66.0    Male          318          91/88          93       NaN   

   Family History  Smoking  Obesity  ...  Sedentary Hours Per Day    Income  \
0             0.0        1        0  ...                 6.615001  261404.0   
1             1.0        1        1  ...                 4.963459  285768.0   
2             0.0        0        0  ...                 9.463426  235282.0   
3             1.0        1        0  ...                 7.648981  125640.0   
4             1.0        1        1  ...                 1.514821  160555.0   

         BMI  Triglycerides  Physical Activity Days Per Week  \
0  31.251233            286                                0   
1  27.194973            235                                1   
2  28.176571            587                                4   
3  36.464704            378                                3   
4  21.809144            231                                1   

   Sleep Hours Per Day    Country      Continent           Hemisphere  \
0                  6.0  Argentina  South America  Southern Hemisphere   
1                  7.0     Canada  North America  Northern Hemisphere   
2                  4.0     France         Europe  Northern Hemisphere   
3                  4.0     Canada  North America  Northern Hemisphere   
4                  5.0   Thailand           Asia  Northern Hemisphere   

   Heart Attack Risk  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 26 columns]

In [ ]:
df

Patient ID   Age     Sex  Cholesterol Blood Pressure  Heart Rate  \
0      BMW7812  67.0       m          208         158/88          72   
1      CZE1114  21.0    male          389         165/93          98   
2      BNI9906  21.0  Female          324         174/99          72   
3      JLN3497  84.0     NaN          383        163/100          73   
4      GFO8847  66.0    Male          318          91/88          93   
..         ...   ...     ...          ...            ...         ...   
994    CPU6882  41.0    Male          284         103/93          69   
995    PDJ6214  79.0  Female          366         109/76          52   
996    PCS6711  43.0    Male          164         172/85          81   
997    XGB9964  31.0  Female          127        147/108          88   
998    NCE3967  70.0  Female          128         118/69          54   

     Diabetes  Family History  Smoking  Obesity  ...  Sedentary Hours Per Day  \
0         0.0             0.0        1        0  ...                 6.615001   
1         1.0             1.0        1        1  ...                 4.963459   
2         1.0             0.0        0        0  ...                 9.463426   
3         1.0             1.0        1        0  ...                 7.648981   
4         NaN             1.0        1        1  ...                 1.514821   
..        ...             ...      ...      ...  ...                      ...   
994       1.0             1.0        1        1  ...                10.109101   
995       0.0             1.0        1        1  ...                10.684838   
996       1.0             1.0        1        0  ...                 7.388219   
997       1.0             1.0        0        1  ...                 2.408175   
998       0.0             0.0        1        0  ...                 0.612978   

       Income        BMI  Triglycerides  Physical Activity Days Per Week  \
0    261404.0  31.251233            286                                0   
1    285768.0  27.194973            235                                1   
2    235282.0  28.176571            587                                4   
3    125640.0  36.464704            378                                3   
4    160555.0  21.809144            231                                1   
..        ...        ...            ...                              ...   
994  295410.0  19.317242            188                                6   
995  190818.0  27.286712            197                                2   
996   84977.0  19.068251            133                                7   
997  101438.0  36.474585            218                                1   
998  252528.0  23.111596            394                                2   

     Sleep Hours Per Day         Country      Continent           Hemisphere  \
0                    6.0       Argentina  South America  Southern Hemisphere   
1                    7.0          Canada  North America  Northern Hemisphere   
2                    4.0          France         Europe  Northern Hemisphere   
3                    4.0          Canada  North America  Northern Hemisphere   
4                    5.0        Thailand           Asia  Northern Hemisphere   
..                   ...             ...            ...                  ...   
994                  6.0     South Korea           Asia  Northern Hemisphere   
995                  5.0           Italy         Europe  Southern Hemisphere   
996                  6.0     New Zealand      Australia  Southern Hemisphere   
997                 10.0  United Kingdom         Europe  Northern Hemisphere   
998                  8.0           Spain         Europe  Southern Hemisphere   

     Heart Attack Risk  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
..                 ...  
994                  1  
995                  0  
996                  1  
997                  0  
998              

In [ ]:

df = df.drop_duplicates(subset=["Patient ID"])

In [ ]:

df.shape

(999, 26)

In [ ]:
import numpy as np
numeric_cols = df.select_dtypes(include=np.number).columns

In [ ]:
numeric_cols

Index(['Age', 'Cholesterol', 'Heart Rate', 'Diabetes', 'Family History',
       'Smoking', 'Obesity', 'Alcohol Consumption', 'Exercise Hours Per Week',
       'Previous Heart Problems', 'Medication Use', 'Stress Level',
       'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides',
       'Physical Activity Days Per Week', 'Sleep Hours Per Day',
       'Heart Attack Risk'],
      dtype='object')

In [ ]:
for col in numeric_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower_bound = Q1 - 1.5 * IQR
  upper_bound = Q3 + 1.5 * IQR
  df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

In [ ]:
df.isnull().sum()

Patient ID                         0
Age                                0
Sex                                1
Cholesterol                        0
Blood Pressure                     0
Heart Rate                         0
Diabetes                           0
Family History                     0
Smoking                            0
Obesity                            0
Alcohol Consumption                0
Exercise Hours Per Week            0
Diet                               0
Previous Heart Problems            0
Medication Use                     0
Stress Level                       0
Sedentary Hours Per Day            0
Income                             0
BMI                                0
Triglycerides                      0
Physical Activity Days Per Week    0
Sleep Hours Per Day                0
Country                            0
Continent                          0
Hemisphere                         0
Heart Attack Risk                  0
dtype: int64

In [ ]:
df.columns

Index(['Patient ID', 'Age', 'Sex', 'Cholesterol', 'Blood Pressure',
       'Heart Rate', 'Diabetes', 'Family History', 'Smoking', 'Obesity',
       'Alcohol Consumption', 'Exercise Hours Per Week', 'Diet',
       'Previous Heart Problems', 'Medication Use', 'Stress Level',
       'Sedentary Hours Per Day', 'Income', 'BMI', 'Triglycerides',
       'Physical Activity Days Per Week', 'Sleep Hours Per Day', 'Country',
       'Continent', 'Hemisphere', 'Heart Attack Risk'],
      dtype='object')

In [ ]:
#Create a list of columns to fill NA values
columns_to_fill = ['Age','Sedentary Hours Per Day','Income','Sleep Hours Per Day']

In [ ]:
#Fill NA values in specified columns with the mean of each column
for col in columns_to_fill:
  df[col] = df[col].fillna(df[col].mean())

In [ ]:
#Create a list of column to fill NA Values
columns_to_fill = ['Diabetes','Family History','Sex']

In [ ]:
#Fill NA Values in specified columns with the mode of categorical columns
for col in columns_to_fill:
  #Calculate the mode of the column
  mode_value = df[col].mode()[0]
  #Replace NAN Values with the mode
  df[col] = df[col].fillna(mode_value)

In [ ]:
# I am removing this cell because it was causing the columns to be dropped before one-hot encoding.
# The missing values were intended to be filled with mean/mode, not dropped.
# df = df.dropna()

category_cols

In [ ]:
category_cols = df.select_dtypes(include='object').columns

for col in category_cols:
  print(col)
  print(df[col].unique())

Patient ID
['BMW7812' 'CZE1114' 'JLN3497' 'WYV0966' 'XXM0972' 'FPS0415' 'VTW9069'
 'DCY3282' 'DXB2434' 'COP0566' 'RQX1211' 'MBI0008' 'LBY7992' 'RDI3071'
 'NCU1956' 'MSW4208' 'TTO9115' 'JDP9221' 'FFF6730' 'DWN2141' 'NXO4034'
 'ENK3334' 'XRL5497' 'DDG3686' 'FLG2019' 'SCZ5893' 'GNK9443' 'TTM1692'
 'DUX2118' 'SQE3213' 'XBP3543' 'ENZ9640' 'QWD3129' 'UBJ2564' 'RRG8947'
 'BFE4900' 'KCY9500' 'JJX0859' 'IKY4481' 'YOD3294' 'OHD3889' 'BDG2694'
 'LTU0801' 'OFU9592' 'WAR7163' 'TFH5628' 'BBJ3290' 'YTR1728' 'AYY8711'
 'TQT8266' 'KTR4778' 'GVI1884' 'SOM8522' 'BNF7145' 'BOK4939' 'DNY3115'
 'SOH9843' 'ICO9779' 'GDC1817' 'DHP4080' 'JPD8131' 'GMI1141' 'QJA1796'
 'WMP6003' 'ADG8069' 'RHR1854' 'GDY0435' 'CQM6221' 'JDS3385' 'JXV3603'
 'OVT8107' 'UIW1798' 'XZD4751' 'OKX6945' 'RKV2333' 'TLA1423' 'NCU4581'
 'XOA9385' 'SLJ3300' 'CFU1297' 'ATI9164' 'HGB5652' 'SIQ8677' 'OGV4421'
 'LDS5768' 'PLR8209' 'YLL9363' 'ITN4331' 'ERP9347' 'UFC0697' 'JFL6450'
 'JKY9288' 'AAX1328' 'XHX1600' 'SDW5368' 'GAN8948' 'AND5753' 'WMN2

In [ ]:
#replace 'Female' with female in sex column
dict1 = {'Female': 'female','f':'female','m':'male','Male':'male'}
df['Sex'] = df['Sex'].replace(dict1)

In [ ]:
dict2 = {'Healty':'Healthy'}

df['Diet'] = df['Diet'].replace(dict2)

In [ ]:
#Splitting the column
split_cols = df['Blood Pressure'].str.split('/',expand=True)
split_cols.columns = ['Systolic','Diastolic']

In [ ]:
#Convert to numeric (optional for calculation)
df['Systolic'] = pd.to_numeric(split_cols['Systolic'])
df['Diastolic'] = pd.to_numeric(split_cols['Diastolic'])

Encoding

In [ ]:
#one-hot encode the gender column data
df = pd.get_dummies(df,columns=['Sex','Diet','Continent','Hemisphere'])

In [ ]:
df.head(1)

Patient ID   Age  Cholesterol Blood Pressure  Heart Rate  Diabetes  \
0    BMW7812  67.0          208         158/88          72       0.0   

   Family History  Smoking  Obesity  Alcohol Consumption  ...  Diet_Healthy  \
0             0.0        1        0                    0  ...         False   

   Diet_Unhealthy  Continent_Africa  Continent_Asia  Continent_Australia  \
0           False             False           False                False   

   Continent_Europe  Continent_North America  Continent_South America  \
0             False                    False                     True   

   Hemisphere_Northern Hemisphere  Hemisphere_Southern Hemisphere  
0                           False                            True  

[1 rows x 37 columns]

Train Test Split

In [ ]:
#Separate the features and target variable
X = df.drop(['Country','Patient ID','Blood Pressure','Heart Attack Risk'], axis=1)
y = df['Heart Attack Risk']

In [ ]:
y.value_counts()

Heart Attack Risk
0    518
1    353
Name: count, dtype: int64

In [ ]:
#Split the data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Logistic Regression

In [ ]:
#Logistic Regression model to predict the outcome
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
y_pred = logreg.predict(X_test)

In [ ]:
#Evaluate the model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

#print these scores
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

# You can also print the confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.5885714285714285
Precision: 0.5714285714285714
Recall: 0.0547945205479452
F1: 0.1

Confusion Matrix:
 [[99  3]
 [69  4]]


In [ ]:
#Decision Tree Model to Predict the OUtcome
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
#Predict the outcome  using the trained model
y_pred = dt.predict(X_test)
y_pred

array([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0])

In [ ]:
#Evaluate the model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

#print these scores
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

# You can also print the confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.5257142857142857
Precision: 0.43243243243243246
Recall: 0.4383561643835616
F1: 0.43537414965986393

Confusion Matrix:
 [[60 42]
 [41 32]]


In [ ]:
#Random Forest Model to predict the outcome
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
#Predict the outcome using the trained model
y_pred = rf.predict(X_test)
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [ ]:
#Evaluate the Model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

# You can also print the confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.52
Precision: 0.2962962962962963
Recall: 0.1095890410958904
F1: 0.16

Confusion Matrix:
 [[83 19]
 [65  8]]


In [ ]:
#XG Boost Model to predict the outcome
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [ ]:
 #Predict the outcome  using the trained model
y_pred = xgb.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0])

In [ ]:
#Evaluate the model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

#print these scores
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1:", f1_score(y_test, y_pred))

# You can also print the confusion matrix
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.56
Precision: 0.4642857142857143
Recall: 0.3561643835616438
F1: 0.40310077519379844

Confusion Matrix:
 [[72 30]
 [47 26]]
